apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc2
spec:
  storageClassName: slow
  resources:
    requests:
      storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
