apiVersion: v1
kind: Pod
metadata:
  name: test-node-affinity
  labels:
    name: test-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - europe-east1
            - europe-west1
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: une-etiquette-de-node
            operator: In
            values:
            - une-valeur-detiquette
            - une-autre-valeur-detiquette 
      - weight: 20
        preference:
          matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - europe-west1
  containers:
  - name: test-node-affinity
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

--- 

apiVersion: v1
kind: Pod
metadata:
  name: test-pod-affinity
  labels:
    name: test-pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: In
            values:
            - S1
        topologyKey: topology.kubernetes.io/zone
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: security
              operator: In
              values:
              - S2
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: test-pod-affinity
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
