apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
spec:
  selector:
    matchLabels:
      app: store
  replicas: 3
  template:
    metadata:
      labels:
        app: store
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app 
                    operator: In 
                    values: 
                    - store
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: redis-server
        image: redis-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
        matchExpressions:
        - key: app 
          operator: In 
          values: 
          - web-store
      topologyKey: "kubernetes.io/hostname"
    podAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector: 
        matchExpressions: 
        - key: app 
          operator: In 
          values: 
          - store
      topologyKey: "kubernetes.io/hostname"
  selector:
    matchLabels:
      app: web-store
  replicas: 3
  template:
    metadata:
      labels:
        app: web-store
    spec:
      containers:
      - name: web-app
        image: nginx-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
