apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priorite-maximale
value: 1000000
description: "Cette classe doit être utilisée que pour les Pods critiques."

---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priorite-maximale
value: 1000000
preemptionPolicy: Never
description: "Cette classe doit être utilisée que pour les Pods critiques."