loki:
  commonConfig:
    replication_factor: 1
  auth_enabled: false
  schemaConfig:
    configs:
      - from: 2024-04-01
        object_store: s3
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h
minio:
  enabled: true
test:
  enabled: false
monitoring:
  selfMonitoring:
    enabled: false
    lokiCanary:
      enabled: false
read:
  replicas: 1
write:
  replicas: 1
backend:
  replicas: 1