apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2
data:
  log_level: INFO

---

apiVersion: v1
kind: Pod
metadata:
  name: env-demo
  labels:
    name: env-demo
spec:
  containers:
  - name: test-conteneur
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env:
      - name: LOG_LEVEL 
        valueFrom: 
          configMapKeyRef:
            name: test-cm-2
            key: log_level
