apiVersion: v1
kind: ConfigMap
metadata:
  name: file-config
data:
  config.ini: |
    [demo]
    log_level = INFO

---

apiVersion: v1
kind: Pod
metadata:
  name: volume-demo
  labels:
    name: volume-demo
spec:
  containers:
  - name: test-conteneur
    image: debian 
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80 
  volumes: 
    - name: config-volume 
      configMap:
       name: file-config
