apiVersion: v1
kind: Secret
metadata:
  name: api-key
type: Opaque
stringData:
  .api-key: ""

---

apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
  labels:
    name: secret-test-pod
spec:
  containers:
  - name: app-conteneur
    image: busybox
    command:
      - ls
      - "-la"
      - "/etc/api"
    volumeMounts:
    - name: api-key-volume
      mountPath: "/etc/api"
      readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes: 
  - name: api-key-volume 
    secret:
      secreName: api-key 

